### ISSUE TITLE
Compilation issue on ntfsusn_recorder->carve_records

### ISSUE THREAD

**Issue by phocean** [simsong/bulk_extractor#104]
Hello,

I am trying to compile the master branch in Ubuntu 18.04.

It fails on this:

```
g++ -DHAVE_CONFIG_H -I. -I..  -I../src/be13_api -I/usr/local/include -DUTC_OFFSET=+0200  -g -pthread -g -O3 -Wall -MD -D_FORTIFY_SOURCE=2 -Wpointer-arith -Wshadow -Wwrite-strings -Wcast-align -Wredundant-decls -Wdisabled-optimization -Wfloat-equal -Wmultichar -Wmissing-noreturn -Woverloaded-virtual -Wsign-promo -funit-at-a-time -Weffc++  -fPIC -D_FORTIFY_SOURCE=2  -MT scan_ntfsusn.o -MD -MP -MF $depbase.Tpo -c -o scan_ntfsusn.o scan_ntfsusn.cpp &&\
mv -f $depbase.Tpo $depbase.Po
scan_ntfsusn.cpp: In function ‘void scan_ntfsusn(const scanner_params&, const recursion_control_block&)’:
scan_ntfsusn.cpp:108:35: error: ‘class feature_recorder’ has no member named ‘carve_records’; did you mean ‘carve_mode’?
                 ntfsusn_recorder->carve_records(sbuf,offset,record_size+padding,"UsnJrnl-J_corrupted");
                                   ^~~~~~~~~~~~~
                                   carve_mode
scan_ntfsusn.cpp:115:39: error: ‘class feature_recorder’ has no member named ‘carve_records’; did you mean ‘carve_mode’?
                     ntfsusn_recorder->carve_records(sbuf,offset,total_record_size,"UsnJrnl-J");
                                       ^~~~~~~~~~~~~
                                       carve_mode
scan_ntfsusn.cpp:117:39: error: ‘class feature_recorder’ has no member named ‘carve_records’; did you mean ‘carve_mode’?
                     ntfsusn_recorder->carve_records(sbuf,offset,total_record_size,"UsnJrnl-J_corrupted");
                                       ^~~~~~~~~~~~~
                                       carve_mode
scan_ntfsusn.cpp:152:31: error: ‘class feature_recorder’ has no member named ‘carve_records’; did you mean ‘carve_mode’?
             ntfsusn_recorder->carve_records(sbuf,offset,total_record_size,"UsnJrnl-J");
                               ^~~~~~~~~~~~~
                               carve_mode
Makefile:973: recipe for target 'scan_ntfsusn.o' failed
make[2]: *** [scan_ntfsusn.o] Error 1
make[2] : on quitte le répertoire « /home/phocean/Sync/Lab/Outils/Inforensique/bulk_extractor/src »
Makefile:466: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1] : on quitte le répertoire « /home/phocean/Sync/Lab/Outils/Inforensique/bulk_extractor »
Makefile:405: recipe for target 'all' failed
make: *** [all] Error 2
```

Any idea ?

**Comment by simsong** [comment]
Which compiler are you using? I can check this out over the weekend.


----
Sent from my phone.

On May 11, 2018, at 4:35 AM, phocean <notifications@github.com> wrote:

Hello,

I am trying to compile the master branch in Ubuntu 18.04.

It fails on this:

g++ -DHAVE_CONFIG_H -I. -I..  -I../src/be13_api -I/usr/local/include -DUTC_OFFSET=+0200  -g -pthread -g -O3 -Wall -MD -D_FORTIFY_SOURCE=2 -Wpointer-arith -Wshadow -Wwrite-strings -Wcast-align -Wredundant-decls -Wdisabled-optimization -Wfloat-equal -Wmultichar -Wmissing-noreturn -Woverloaded-virtual -Wsign-promo -funit-at-a-time -Weffc++  -fPIC -D_FORTIFY_SOURCE=2  -MT scan_ntfsusn.o -MD -MP -MF $depbase.Tpo -c -o scan_ntfsusn.o scan_ntfsusn.cpp &&\
mv -f $depbase.Tpo $depbase.Po
scan_ntfsusn.cpp: In function ‘void scan_ntfsusn(const scanner_params&, const recursion_control_block&)’:
scan_ntfsusn.cpp:108:35: error: ‘class feature_recorder’ has no member named ‘carve_records’; did you mean ‘carve_mode’?
                 ntfsusn_recorder->carve_records(sbuf,offset,record_size+padding,"UsnJrnl-J_corrupted");
                                   ^~~~~~~~~~~~~
                                   carve_mode
scan_ntfsusn.cpp:115:39: error: ‘class feature_recorder’ has no member named ‘carve_records’; did you mean ‘carve_mode’?
                     ntfsusn_recorder->carve_records(sbuf,offset,total_record_size,"UsnJrnl-J");
                                       ^~~~~~~~~~~~~
                                       carve_mode
scan_ntfsusn.cpp:117:39: error: ‘class feature_recorder’ has no member named ‘carve_records’; did you mean ‘carve_mode’?
                     ntfsusn_recorder->carve_records(sbuf,offset,total_record_size,"UsnJrnl-J_corrupted");
                                       ^~~~~~~~~~~~~
                                       carve_mode
scan_ntfsusn.cpp:152:31: error: ‘class feature_recorder’ has no member named ‘carve_records’; did you mean ‘carve_mode’?
             ntfsusn_recorder->carve_records(sbuf,offset,total_record_size,"UsnJrnl-J");
                               ^~~~~~~~~~~~~
                               carve_mode
Makefile:973: recipe for target 'scan_ntfsusn.o' failed
make[2]: *** [scan_ntfsusn.o] Error 1
make[2] : on quitte le répertoire « /home/phocean/Sync/Lab/Outils/Inforensique/bulk_extractor/src »
Makefile:466: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1] : on quitte le répertoire « /home/phocean/Sync/Lab/Outils/Inforensique/bulk_extractor »
Makefile:405: recipe for target 'all' failed
make: *** [all] Error 2
Any idea ?

**Comment by phocean** [comment]
I hope this answers to your question:

```bash
➤  g++ --version
g++ (Ubuntu 7.3.0-16ubuntu3) 7.3.0
➤  gcc --version
gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0
```

**Comment by simsong** [comment]
Yes. Wow, Version 7. I'll give it a try.

**Comment by simsong** [comment]
Okay. I just got it to compile on a fresh install of Ubuntu 18.04 with gcc 7.3.0.

Add the packages you need with: etc/CONFIGURE_UBUNTU18.bash

in 774acfc..ecb627d

**Comment by phocean** [comment]
It worked for me too, thanks !

Note that it should probably be:

```
git clone --recursive https://github.com/simsong/bulk_extractor.git
```

as the SSH transport would lead to a permission error for users.

**Comment by simsong** [comment]
Thanks for your help

**Comment by th-sid1** [comment]
> It worked for me too, thanks !
> 
> Note that it should probably be:
> 
> ```
> git clone --recursive https://github.com/simsong/bulk_extractor.git
> ```
> 
> as the SSH transport would lead to a permission error for users.

@simsong, request you to please include above `git` command w/ `--recursive`  option to install page ... I spent couple of hours figuring out this trick

**Comment by simsong** [comment]
Where is the `git clone` command that I need to fix?
