### ISSUE TITLE
bulk_extractor fails to compile on fresh 15.10 (hashdb issue)

### ISSUE THREAD

**Issue by schmiedecker** [simsong/bulk_extractor#76]
On a clean Ubuntu 15.10, compiling bulk_extractor fails with the following error. hashdb is installed in the most recent version (3.0.0-alpha-2), probably related to the recent changes to the hashdb interfaces (paging @BruceMty).

Compilation error and history below.

***

g++ -DHAVE_CONFIG_H -I. -I..  -I../src/be13_api -I/usr/local/include -DUTC_OFFSET=+0200  -g -pthread -g -O3 -std=c++11 -Wall -MD -D_FORTIFY_SOURCE=2 -Wpointer-arith -Wshadow -Wwrite-strings -Wcast-align -Wredundant-decls -Wdisabled-optimization -Wfloat-equal -Wmultichar -Wmissing-noreturn -Woverloaded-virtual -Wsign-promo -funit-at-a-time -Weffc++  -fPIC -D_FORTIFY_SOURCE=2  -MT scan_hashdb.o -MD -MP -MF $depbase.Tpo -c -o scan_hashdb.o scan_hashdb.cpp &&\
mv -f $depbase.Tpo $depbase.Po
scan_hashdb.cpp: In function ‘void do_scan(const scanner_params&, const recursion_control_block&)’:
scan_hashdb.cpp:551:47: error: ‘class hashdb::scan_manager_t’ has no member named ‘find_expanded_hash’
         std::string json_text = scan_manager->find_expanded_hash(binary_hash);
                                               ^
Makefile:970: recipe for target 'scan_hashdb.o' failed
make[2]: *** [scan_hashdb.o] Error 1
make[2]: Leaving directory '/home/lala/bulk_extractor/src'
Makefile:465: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/lala/bulk_extractor'
Makefile:404: recipe for target 'all' failed
make: *** [all] Error 2

lala@lala:~/bulk_extractor$ history
    1  git
    2  ping google.de
    3  sudo apt-get upgrade
    4  apt-cache policy build-essential
    5  sudo apt-get install build-essential
    6  sudo apt-get install git
    7  sudo apt-get install libssl-dev
    8  sudo apt-get install libtool libtool-bin
    9  git clone https://github.com/NPS-DEEP/hashdb.git
   10  cd hashdb
   11  sh bootstrap.sh
   12  sudo apt-get install automake
   13  sh bootstrap.sh
   14  ./configure
   15  make
   16  sudo make install
   17  sudo apt-get install flex libewf-dev
   18  sudo apt-get install libtre-dev
   19  sudo apt-get install libafflib-dev
   20  sudo apt-cache lib sqlite dev
   21  sudo apt-cache search lib sqlite dev
   22  sudo apt-get install libsqlite3-dev
   23  sudo apt-cache search libxml
   24* sudo apt-cache search libxml2-
   25  sudo apt-get install libxml2-dev
   26  hashdb
   27  cd ..
   28  git clone --recursive https://github.com/simsong/bulk_extractor.git
   29  cd bulk_extractor/
   30  sh bootstrap.sh
   31  ./configure
   32  make
   33  history
   34  hashdb|more
   35  history
   36  bulk_extractor
   37  ll
   38  git pull
   39  cfd ..
   40  cd ../bulk_extractor/
   41  cd ../hashdb/
   42  git pull
   43  sh bootstrap.sh 
   44  ./configure --with-pic
   45  sudo apt-get update
   46  sudo apt-get dist-upgrade
   47  make
   48  sudo make install
   49  cd ../bulk_extractor/
   50  ls
   51  sh bootstrap.sh 
   52  ./configure
   53  make

**Comment by BruceMty** [comment]
Yes, hashdb version 3.0.0-alpha-2 interfaces changed, making it incompatible with all but the master branch of bulk_extractor.  If you want hashdb, I strongly recommend migrating to hashdb v3.0 and using the master branch of bulk_extractor.  If you don't need hashdb, uninstall it and then run bulk_extractor's configure script so that bulk_extractor will build without hashdb.


________________________________

**Comment by BruceMty** [comment]
Oh, from history, I see that both were from master branch.  bulk_extractor was behind.  This should be fixed as of April 12.
